---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Pause for job to complete."
      ansible.builtin.pause:
        seconds: 30

    - name: "Check if 'mongodb' namespace exists."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "mongodb-instance"
      register: namespace_mongodb
      failed_when: false
      changed_when: false

    - name: Assert that 'mongodb' namespace does not exist
      ansible.builtin.assert:
        that: namespace_mongodb['resources'] | length == 0
