---
galaxy_info:
  description: "Install and configure Mailcrab on Kubernetes using the official Helm chart"
  role_name: "mailcrab"
  author: "Cl√©ment Hubert"

  license: "MPL2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "kubernetes"
    - "mail"
    - "mailhog"
    - "mailcrab"

dependencies: []
