---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Pause for job to complete."
      ansible.builtin.pause:
        seconds: 120

    - name: "Get 'mongodb' namespace info."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "mongodb"
      register: namespace_mongodb

    - name: "Assert that 'mongodb' namespace is active"
      ansible.builtin.assert:
        that: namespace_mongodb['resources'][0]['status']['phase'] == "Active"

    - name: "Get 'mongodb-kubernetes-operator' info."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "mongodb-kubernetes-operator"
        namespace: "mongodb"
      register: operator_deployment

    - name: "Assert that 'mongodb operator' is deployed"
      ansible.builtin.assert:
        that: operator_deployment['resources'][0]['status']['availableReplicas'] == 1

    - name: "Get 'mongodb-database StatefullSet' service info."
      kubernetes.core.k8s_info:
        kind: "StatefulSet"
        name: "mongodb-database-mongodb-instance"
        namespace: "mongodb"
      register: stateful_set

    - name: "Assert that 'mongodb-database' statefullset is deployed"
      ansible.builtin.assert:
        that: stateful_set['resources'][0]['status']['availableReplicas'] == 1
