---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Pause for deployment to complete."
      ansible.builtin.pause:
        seconds: 60

    - name: "Get 'gatus' namespace info."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "gatus"
      register: namespace_gatus

    - name: Assert that 'gatus' namespace is active
      ansible.builtin.assert:
        that: namespace_gatus['resources'][0]['status']['phase'] == "Active"

    - name: "Get 'gatus' Deployment info."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "gatus"
        namespace: "gatus"
      register: gatus_deployment

    - name: "Assert that 'gatus' Deployment is deployed"
      ansible.builtin.assert:
        that: gatus_deployment['resources'] | length > 0

    - name: "Assert that 'gatus' Deployment has ready replicas"
      ansible.builtin.assert:
        that: gatus_deployment['resources'][0]['status']['readyReplicas'] | default(0) >= 1
