---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    mailcrab_enabled: false
  tasks:
    - name: "Remove Mailcrab"
      ansible.builtin.import_role:
        name: "mailcrab"
