---
galaxy_info:
  description: "Install and configure Uptime Kuma application on kubernetes"
  role_name: "uptime_kuma"
  author: "Cl√©ment Hubert"

  license: "MLP2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "kubernetes"
    - "uptime"
    - "kuma"
    - "monitoring"

dependencies: []
