---
- name: "Create external-dns namespace"
  kubernetes.core.k8s:
    name: "{{ external_dns_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Add external-dns helm repo"
  kubernetes.core.helm_repository:
    name: "{{ external_dns_helm_repo_name }}"
    repo_url: "{{ external_dns_helm_repo_url }}"

- name: "Install external-dns helm package"
  kubernetes.core.helm:
    name: "{{ external_dns_deployment_name }}"
    namespace: "{{ external_dns_namespace }}"
    chart_ref: "{{ external_dns_helm_chart_ref }}"
    chart_version: "{{ external_dns_helm_chart_version }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('ansible.builtin.template', 'external_dns_helm_values.yml.j2') | from_yaml }}"
    wait: true
