---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Pause for cleanup to complete."
      ansible.builtin.pause:
        seconds: 30

    - name: "Check if 'gatus' namespace exists."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "gatus"
      register: namespace_gatus
      failed_when: false
      changed_when: false

    - name: Assert that 'gatus' namespace does not exist
      ansible.builtin.assert:
        that: namespace_gatus['resources'] | length == 0
