---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    uptime_kuma_enabled: false
  tasks:
    - name: "Install Uptime Kuma"
      ansible.builtin.import_role:
        name: "uptime_kuma"
