---
- name: "Uninstall MongoDb Operator helm package"
  kubernetes.core.helm:
    name: "{{ mongodb_operator_deployment_name }}"
    namespace: "{{ mongodb_operator_namespace }}"
    state: "absent"
    chart_ref: "{{ mongodb_operator_helm_chart_ref }}"
    chart_version: "{{ mongodb_operator_helm_version }}"
    wait: true

- name: "Remove MongoDb Operator helm repo"
  kubernetes.core.helm_repository:
    name: "{{ mongodb_operator_helm_repo_name }}"
    repo_url: "{{ mongodb_operator_helm_repo_url }}"
    state: "absent"

- name: "Remove MongoDb Operator namespace"
  kubernetes.core.k8s:
    name: "{{ mongodb_operator_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "absent"
