---

- name: "Create Uptime Kuma namespace"
  kubernetes.core.k8s:
    name: "{{ uptime_kuma_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Add Uptime Kuma helm repo"
  kubernetes.core.helm_repository:
    name: "{{ uptime_kuma_helm_repo_name }}"
    repo_url: "{{ uptime_kuma_helm_repo_url }}"

- name: "Install Uptime Kuma helm package"
  kubernetes.core.helm:
    name: "{{ uptime_kuma_release_name }}"
    namespace: "{{ uptime_kuma_namespace }}"
    state: "present"
    chart_ref: "{{ uptime_kuma_helm_chart_ref }}"
    chart_version: "{{ uptime_kuma_helm_version }}"
    update_repo_cache: true
    values: "{{ lookup('ansible.builtin.template', 'uptime_kuma_helm_values.yml.j2') | from_yaml }}"
    wait: "{{ uptime_kuma_wait_install }}"
