---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    external_dns_provider_name: "inmemory"
  tasks:
    - name: "Install External-DNS"
      ansible.builtin.import_role:
        name: "external_dns"
