---
mongodb_operator_helm_repo_name: "mongodb"
mongodb_operator_helm_repo_url: "https://mongodb.github.io/helm-charts"
mongodb_operator_helm_chart_ref: "{{ mongodb_operator_helm_repo_name }}/mongodb-kubernetes"
