---
# tasks file for atlantis
- name: "Include setup when enabled"
  ansible.builtin.include_tasks: "setup.yml"
  when: atlantis_enabled

- name: "Include cleanup when disabled"
  ansible.builtin.include_tasks: "cleanup.yml"
  when: not atlantis_enabled
