---
- name: "Create atlantis namespace"
  kubernetes.core.k8s:
    name: "{{ atlantis_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Add atlantis helm repo"
  kubernetes.core.helm_repository:
    name: "{{ atlantis_helm_repo_name }}"
    repo_url: "{{ atlantis_helm_repo_url }}"

- name: "Install atlantis helm package"
  kubernetes.core.helm:
    name: "{{ atlantis_deployment_name }}"
    namespace: "{{ atlantis_namespace }}"
    state: "present"
    chart_ref: "{{ atlantis_helm_chart_ref }}"
    chart_version: "{{ atlantis_helm_version }}"
    update_repo_cache: true
    values: "{{ lookup('ansible.builtin.template', 'atlantis_helm_values.yml.j2') | from_yaml }}"
    wait: "{{ atlantis_wait_install }}"
