---
# defaults file for uptime-kuma

# @var uptime_kuma_enabled
# @var uptime_kuma_enabled:type: boolean
# @var uptime_kuma_enabled:description: >
# Should uptime-kuma helm chart be installed
uptime_kuma_enabled: true

# @var uptime_kuma_namespace
# @var uptime_kuma_namespace:type: string
# @var uptime_kuma_namespace:description: >
# K8s namespace to install the uptime-kuma chart
uptime_kuma_namespace: "uptime-kuma"

# @var uptime_kuma_helm_version
# @var uptime_kuma_helm_version:type: string
# @var uptime_kuma_helm_version:description: >
# Helm chart version to install
uptime_kuma_helm_version: "2.21.3"

# @var uptime_kuma_deployment_name
# @var uptime_kuma_deployment_name:type: string
# @var uptime_kuma_deployment_name:description: >
# Helm chart deployment name
uptime_kuma_release_name: "uptime-kuma"

# @var uptime_kuma_wait_install
# @var uptime_kuma_wait_install:type: boolean
# @var uptime_kuma_wait_install:description: >
# Wait for helm install to complete
uptime_kuma_wait_install: true

# @var uptime_kuma_deployment_type
# @var uptime_kuma_deployment_type:type: string
# @var uptime_kuma_deployment_type:description: >
# Install as deployment or statefulset
uptime_kuma_deployment_type: "deployment"

# @var uptime_kuma_service_account_create
# @var uptime_kuma_service_account_create:type: boolean
# @var uptime_kuma_service_account_create:description: >
# Specifies whether a service account should be created
uptime_kuma_service_account_create: true

# @var uptime_kuma_service_account_create
# @var uptime_kuma_service_account_create:type: dict
# @var uptime_kuma_service_account_create:description: >
# Annotations to add to the service account
uptime_kuma_service_account_annotations: {}

# @var uptime_kuma_service_account_name
# @var uptime_kuma_service_account_name:type: string
# @var uptime_kuma_service_account_name:description: >
# The name of the service account to use, autogenerated if empty
uptime_kuma_service_account_name: ""

# @var uptime_kuma_pod_annotations
# @var uptime_kuma_pod_annotations:type: dict
# @var uptime_kuma_pod_annotations:description: >
# Annotations for pod
uptime_kuma_pod_annotations: {}

# @var uptime_kuma_pod_labels
# @var uptime_kuma_pod_labels:type: dict
# @var uptime_kuma_pod_labels:description: >
# Labels for pod
# @var uptime_kuma_pod_labels:example: >
# uptime_kuma_pod_labels:
#   app: uptime-kuma
uptime_kuma_pod_labels: {}

# @var uptime_kuma_pod_env
# @var uptime_kuma_pod_env:type: dict
# @var uptime_kuma_pod_env:description: >
# Optional additional environment variables
# @var uptime_kuma_pod_env:example: >
# uptime_kuma_pod_env:
#  - name: "A_VARIABLE"
#    value: "a-value"
uptime_kuma_pod_env: []

# @var uptime_kuma_pod_security_context
# @var uptime_kuma_pod_security_context:type: dict
# @var uptime_kuma_pod_security_context:description: >
# Security context for pods
# @var uptime_kuma_pod_security_context:example: >
# uptime_kuma_pod_security_context:
#   fsGroup: 2000
uptime_kuma_pod_security_context: {}

# @var uptime_kuma_security_context
# @var uptime_kuma_security_context:type: dict
# @var uptime_kuma_security_context:description: >
# Security context
# @var uptime_kuma_security_context:example: >
# uptime_kuma_security_context:
#    capabilities:
#      drop:
#      - ALL
#    readOnlyRootFilesystem: true
#    runAsNonRoot: true
#    runAsUser: 1000
uptime_kuma_security_context: {}

# @var uptime_kuma_ingress_enabled
# @var uptime_kuma_ingress_enabled:type: dict
# @var uptime_kuma_ingress_enabled:description: >
# Enable ingress
uptime_kuma_ingress_enabled: false

# @var uptime_kuma_ingress_classname
# @var uptime_kuma_ingress_classname:type: dict
# @var uptime_kuma_ingress_classname:description: >
# Ingress classname
# @var uptime_kuma_ingress_classname:example: >
# uptime_kuma_ingress_classname: "nginx"

# @var uptime_kuma_ingress_labels
# @var uptime_kuma_ingress_labels:type: dict
# @var uptime_kuma_ingress_labels:description: >
# Ingress labels
# @var uptime_kuma_ingress_labels:example: >
# uptime_kuma_ingress_labels:
#   vhost: uptime-kuma.company.corp
uptime_kuma_ingress_labels: {}

# @var uptime_kuma_ingress_annotations
# @var uptime_kuma_ingress_annotations:type: dict
# @var uptime_kuma_ingress_annotations:description: >
# Ingress annotations
# @var uptime_kuma_ingress_annotations:example: >
# uptime_kuma_ingress_annotations:
#  nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
#     nginx.ingress.kubernetes.io/server-snippets: |
#       location / {
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_http_version 1.1;
#         proxy_set_header X-Forwarded-Host $http_host;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_set_header X-Forwarded-For $remote_addr;
#         proxy_set_header Host $host;
#         proxy_set_header Connection "upgrade";
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header   Upgrade $http_upgrade;
#         proxy_cache_bypass $http_upgrade;
#       }
uptime_kuma_ingress_annotations: {}

# @var uptime_kuma_resources
# @var uptime_kuma_resources:type: dict
# @var uptime_kuma_resources:description: >
# Ingress resources limits
# @var uptime_kuma_resources:example: >
# uptime_kuma_resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
uptime_kuma_resources: {}

# @var uptime_kuma_liveness_probe_enabled
# @var uptime_kuma_liveness_probe_enabled:type: boolean
# @var uptime_kuma_liveness_probe_enabled:description: >
# Enable liveness probe
uptime_kuma_liveness_probe_enabled: true

# @var uptime_kuma_readiness_probe_enabled
# @var uptime_kuma_readiness_probe_enabled:type: boolean
# @var uptime_kuma_readiness_probe_enabled:description: >
# Enable readiness probe
uptime_kuma_readiness_probe_enabled: true

# @var uptime_kuma_volume_enabled
# @var uptime_kuma_volume_enabled:type: boolean
# @var uptime_kuma_volume_enabled:description: >
# Enable volume for statefulset
uptime_kuma_volume_enabled: true

# @var uptime_kuma_volume_access_mode
# @var uptime_kuma_volume_access_mode:type: boolean
# @var uptime_kuma_volume_access_mode:description: >
# Statefulset volume access mode
uptime_kuma_volume_access_mode: "ReadWriteOnce"

# @var uptime_kuma_volume_size
# @var uptime_kuma_volume_size:type: boolean
# @var uptime_kuma_volume_size:description: >
# Statefulset volume size
uptime_kuma_volume_size: "4Gi"

# @var uptime_kuma_volume_existing_claim
# @var uptime_kuma_volume_existing_claim:type: boolean
# @var uptime_kuma_volume_existing_claim:description: >
# Existing volume to use in statefulset
uptime_kuma_volume_existing_claim: ""

# @var uptime_kuma_mariadb_enabled
# @var uptime_kuma_mariadb_enabled:type: boolean
# @var uptime_kuma_mariadb_enabled:description: >
# Enabled mariabd support
uptime_kuma_mariadb_enabled: false
