---
galaxy_info:
  description: "Install and configure Gatus on kubernetes"
  role_name: "gatus"
  author: "Cl√©ment Hubert"

  license: "MLP2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "kubernetes"
    - "gatus"
    - "status"
    - "monitoring"

dependencies: []
