---
# @var argocd_enabled
# @var argocd_enabled:type: boolean
# @var argocd_enabled:description: >
# Should ArgoCD helm chart be installed
argocd_enabled: true

# @var argocd_namespace
# @var argocd_namespace:type: string
# @var argocd_namespace:description: >
# K8s namespace to install the ArgoCD chart
argocd_namespace: "argocd"

# @var argocd_helm_chart_version
# @var argocd_helm_chart_version:type: string
# @var argocd_helm_chart_version:description: >
# Helm chart version to install
argocd_helm_chart_version: 9.4.5

# @var argocd_deployment_name
# @var argocd_deployment_name:type: string
# @var argocd_deployment_name:description: >
# Deployment name for ArgoCD helm chart
argocd_deployment_name: "argocd"

# @var argocd_server_ingress_enabled
# @var argocd_server_ingress_enabled:type: boolean
# @var argocd_server_ingress_enabled:description: >
# Enable ingress for ArgoCD server
argocd_server_ingress_enabled: false

# @var argocd_server_ingress_class_name
# @var argocd_server_ingress_class_name:type: string
# @var argocd_server_ingress_class_name:description: >
# Ingress classname for ArgoCD server ingress
argocd_server_ingress_class_name: null

# @var argocd_server_ingress_hostname
# @var argocd_server_ingress_hostname:type: string
# @var argocd_server_ingress_hostname:description: >
# Hostname for ArgoCD server ingress
argocd_server_ingress_hostname: null

# @var argocd_server_ingress_tls_enabled
# @var argocd_server_ingress_tls_enabled:type: boolean
# @var argocd_server_ingress_tls_enabled:description: >
# Enable TLS for ArgoCD server ingress
argocd_server_ingress_tls_enabled: false

# @var argocd_server_ingress_tls_secret_name
# @var argocd_server_ingress_tls_secret_name:type: string
# @var argocd_server_ingress_tls_secret_name:description: >
# Secret name for ArgoCD server TLS certificate
argocd_server_ingress_tls_secret_name: null

# @var argocd_server_ingress_annotations
# @var argocd_server_ingress_annotations:type: dict
# @var argocd_server_ingress_annotations:description: >
# Annotations for ArgoCD server ingress
argocd_server_ingress_annotations: {}

# @var argocd_server_ingress_labels
# @var argocd_server_ingress_labels:type: dict
# @var argocd_server_ingress_labels:description: >
# Labels for ArgoCD server ingress
argocd_server_ingress_labels: {}

# @var argocd_server_resources
# @var argocd_server_resources:type: dict
# @var argocd_server_resources:description: >
# ArgoCD server resources requests and limits
argocd_server_resources: {}

# @var argocd_repo_server_resources
# @var argocd_repo_server_resources:type: dict
# @var argocd_repo_server_resources:description: >
# ArgoCD repo server resources requests and limits
argocd_repo_server_resources: {}

# @var argocd_application_controller_resources
# @var argocd_application_controller_resources:type: dict
# @var argocd_application_controller_resources:description: >
# ArgoCD application controller resources requests and limits
argocd_application_controller_resources: {}

# @var argocd_redis_resources
# @var argocd_redis_resources:type: dict
# @var argocd_redis_resources:description: >
# ArgoCD redis resources requests and limits
argocd_redis_resources: {}

# @var argocd_controller_replicas
# @var argocd_controller_replicas:type: int
# @var argocd_controller_replicas:description: >
# Number of ArgoCD application controller replicas
argocd_controller_replicas: 1

# @var argocd_server_replicas
# @var argocd_server_replicas:type: int
# @var argocd_server_replicas:description: >
# Number of ArgoCD server replicas
argocd_server_replicas: 1

# @var argocd_repo_server_replicas
# @var argocd_repo_server_replicas:type: int
# @var argocd_repo_server_replicas:description: >
# Number of ArgoCD repo server replicas
argocd_repo_server_replicas: 1

# @var argocd_additional_config
# @var argocd_additional_config:type: dict
# @var argocd_additional_config:description: >
# Additional configuration to merge with the helm values.
# This allows to add any configuration not explicitly exposed by this role.
argocd_additional_config: {}

# @var argocd_clusters
# @var argocd_clusters:type: list
# @var argocd_clusters:description: >
# List of clusters to add to ArgoCD
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters
argocd_clusters: []

# @var argocd_repositories
# @var argocd_repositories:type: list
# @var argocd_repositories:description: >
# List of repositories to add to ArgoCD
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories
# @var argocd_repositories:example: >
# argocd_repositories:
#   - name: "private-repo"
#     type: "git"
#     parameters:
#       url: "git@github.com:argoproj/my-private-repository.git"
#       sshPrivateKey: "{{ lookup('file', '~/.ssh/id_rsa') }}"
argocd_repositories: []

# @var argocd_projects
# @var argocd_projects:type: list
# @var argocd_projects:description: >
# List of projects to add to ArgoCD
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects
argocd_projects: []

# @var argocd_applications
# @var argocd_applications:type: list
# @var argocd_applications:description: >
# List of applications to add to ArgoCD
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications
argocd_applications: []


# @var argocd_default_finalizers
# @var argocd_default_finalizers:type: list
# @var argocd_default_finalizers:description: >
# Default finalizers for ArgoCD projects
argocd_default_finalizers:
  - resources-finalizer.argocd.argoproj.io

# @var argocd_application_sets
# @var argocd_application_sets:type: list
# @var argocd_application_sets:description: >
# List of application sets to add to ArgoCD
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#application-sets
argocd_application_sets: []

# @var argocd_application_sets_default_go_template_options
# @var argocd_application_sets_default_go_template_options:type: list
# @var argocd_application_sets_default_go_template_options:description: >
# Default go template options for application sets
argocd_application_sets_default_go_template_options:
  - "missingkey=error"
