---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    atlantis_enabled: false
  tasks:
    - name: "Remove Atlantis"
      ansible.builtin.import_role:
        name: "atlantis"
