---
# tasks file for gatus
- name: "Include setup when enabled"
  ansible.builtin.include_tasks: "setup.yml"
  when: gatus_enabled

- name: "Include cleanup when disabled"
  ansible.builtin.include_tasks: "cleanup.yml"
  when: not gatus_enabled
